version: '3'


services:

  mysql:
    container_name: hacker_iot_mysql
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root' # TODO: Change this
      MYSQL_USER: 'gs'
      MYSQL_PASS: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'TRUE'
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--ft_min_word_len=2', '--innodb_ft_min_token_size=2', '--sql-mode=NO_ENGINE_SUBSTITUTION']
    volumes:
      - ./persistance_data/mysql-data:/var/lib/mysql:cached
    ports:
      - "3306:3306"
    networks:
      - hackeriot-nw

  redis:
    container_name: hacker_iot_redis
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - hackeriot-nw


volumes:
  my-build-cached:
  my-build-target:
  elastic-datavolume:

networks:
  hackeriot-nw:
    driver: bridge



